const SHOP_DATA = [
  {
    id: 0,
    routeName: "shop/all-occasions",
    title: "All Occasions",
    items: [
      {
        imageUrl:
          "https://res.cloudinary.com/dgdnpkfun/image/upload/v1673493607/arrangements/brightenDay_fanxij.png",
        id: 42,
        favorite: "add",
        delete: "delete",
        name: "Brighten Up Your Day Special",
        emoji: "🌷",
        description:
          "Part of our daily special and it's available for you to enjoy.",
        pricingText: 50,
        quantity: 1,
        category: "all-occasions",
        numReviews: 0,
        comments: [],
        brand: "",
        published: true,
        countInStock: true,
        stores: ["home", "all-occasions"],
      },
      {
        imageUrl:
          "https://res.cloudinary.com/dgdnpkfun/image/upload/v1673493221/arrangements/winterIsComing_isjbjq.png",
        id: 41,
        favorite: "add",
        delete: "delete",
        name: "Winter is Here",
        emoji: "🌹",
        description:
          "The arrangement I make is suited for diffreent occasions . Whether for graduation, birthday or just a simple Thank. You gesture. This compact size and the round shape makes this bouquet so adorable. This bouquet also can be placed in the vase after the event is done and turn into a home decor or even centerpiece. Mixed flowers and use mostly bright and happy colors that give a young look, energetic and casual.",
        pricingText: 47,
        quantity: 1,
        category: "all-occasions",
        numReviews: 0,
        comments: [],
        brand: "",
        published: true,
        countInStock: true,
        stores: ["home", "all-occasions"],
      },
      {
        imageUrl:
          "https://res.cloudinary.com/dgdnpkfun/image/upload/v1673561727/arrangements/SweetLily_le3w2b.png",
        id: 43,
        favorite: "add",
        delete: "delete",
        name: "Sweet Lily",
        emoji: "🌸",
        description:
          "Welcome the season of fall into your home with this delicate and beautiful arrangement of different varieties of lilies. Crafted with other seasonal flowers woven throughout the entirety of the arrangement .Designer’s top choice with classic glass vase. Vase included",
        pricingText: 64,
        quantity: 1,
        category: "all-occasions",
        numReviews: 0,
        comments: [],
        brand: "",
        published: true,
        countInStock: true,
        stores: ["home", "all-occasions"],
      },
      {
        imageUrl:
          "https://res.cloudinary.com/dgdnpkfun/image/upload/v1656003850/arrangements/phaelenopsis-orchid-garden_seodpx.png",
        id: 5,
        favorite: "add",
        delete: "delete",
        name: "Orchid Garden",
        emoji: "💮",
        description:
          "A perfect bouquet to give to anybody to express your love, care, congratulations, anniversary, birthday, thank you, miss you, get well etc. The bouquet made as one side view and a bit in long stems they are mixed spring flowers variety of mum, ]chrysanthemums, rose, lisianthus, tulips, spray rose and some greenish with a variety of foliages to make it so elegant in your hand or when it’s placed in the glass water vase (included) on table as a home decor.",
        pricingText: 50,
        quantity: 1,
        category: "all-occasions",
        numReviews: 0,
        comments: [],
        brand: "",
        published: true,
        countInStock: true,
        stores: ["home", "all-occasions"],
      },
      {
        imageUrl:
          "https://res.cloudinary.com/dgdnpkfun/image/upload/v1656003850/arrangements/neon-light-city-design_jgzsyq.png",
        id: 6,
        favorite: "add",
        delete: "delete",
        name: "Neon Light City",
        emoji: "🌲",
        description:
          "The arrangement I make specially for graduation, bridesmaids or birthday girls, the compact size and the round shape makes this bouquet so adorable. This bouquet also can be placed in the vase after the event is done and turn into a home decor or even centerpiece. Mixed spring flowers and use mostly bright and happy colors that give a young look, energetic and casual.",
        pricingText: 42,
        quantity: 1,
        category: "all-occasions",
        numReviews: 0,
        comments: [],
        brand: "",
        published: true,
        countInStock: true,
        stores: ["home", "all-occasions"],
      },
    ],
  },
  {
    id: 1,
    routeName: "shop/holidays",
    title: "Holidays",
    items: [
      {
        id: 61,
        imageUrl:
          "https://res.cloudinary.com/dgdnpkfun/image/upload/v1684027844/love-you-mom_ggmrij.png",
        favorite: "add",
        delete: "delete",
        name: "Love You, Mom!",
        emoji: "🌹",
        description:
          "This unique centerpiece’ design is a way to celebrate Mother’s Day. Beautifully arranged with many seasonal blooms, vibrant colors and the fresh scents make a great atmosphere for Mom.. Perfectly situated in her dining table. You can supersize your love for Mom and order her a larger piece. Both arrangements comes with a note.",
        pricingText: 99,
        quantity: 1,
        category: "holidays",
        numReviews: 0,
        comments: [],
        brand: "",
        published: true,
        countInStock: true,
        stores: ["home", "holidays", "deals"],
      },
      {
        imageUrl:
          "https://res.cloudinary.com/dgdnpkfun/image/upload/v1684028212/thanks-mom_nilxyf.png",
        id: 62,
        favorite: "add",
        delete: "delete",
        name: "Thanks, Mom!",
        emoji: "🌹",
        description:
          "Another way to express your love and thanks to your Mom’s by sending her this elegant, gorgeous flowers arrangement on Mother’s Day. A combo premium flowers such Ranunculus, , Frisia, Lysianthus , Roses, and others to give a modern look arrangement. Free a card with message!",
        pricingText: 129,
        quantity: 1,
        category: "holidays",
        numReviews: 0,
        comments: [],
        brand: "",
        published: true,
        countInStock: true,
        stores: ["home", "holidays", "deals"],
      },
      {
        imageUrl:
          "https://res.cloudinary.com/dgdnpkfun/image/upload/v1684028474/best-mom-ever_vijakj.png",
        id: 63,
        favorite: "add",
        delete: "delete",
        name: "Best Mom Ever",
        emoji: "🌹",
        description:
          "A mix of roses, Peruvian lilies, Gerbera daises, wax flowers, eucalyptus. Wrapped beautifully for her. You can include a short note for personal touch on us.",
        pricingText: 79,
        quantity: 1,
        category: "holidays",
        numReviews: 0,
        comments: [],
        brand: "",
        published: true,
        countInStock: true,
        stores: ["home", "holidays", "deals"],
      },
      {
        imageUrl:
          "https://res.cloudinary.com/dgdnpkfun/image/upload/v1684028777/fabulous-mom_ui3yyf.png",
        id: 64,
        favorite: "add",
        delete: "delete",
        name: "Fabulous Mom",
        emoji: "🌹",
        description:
          "Every Mom deserve the very best in this special day. Why not an elegant bouquet . Free note with a short message.",
        pricingText: 99,
        quantity: 1,
        category: "holidays",
        numReviews: 0,
        comments: [],
        brand: "",
        published: true,
        countInStock: true,
        stores: ["home", "holidays", "deals"],
      },
      {
        imageUrl:
          "https://res.cloudinary.com/dgdnpkfun/image/upload/v1684029184/fifteen-elegant-classic-roses-for-moms_hngd54.png",
        id: 62,
        favorite: "add",
        delete: "delete",
        name: "15 Elegant Classic Roses for Moms",
        emoji: "🌹",
        description:
          "15 hand picked classic roses, beautifully arranged in a metallic glass vase. Letting mom know how fabulous she has been. A token of gratitude and love onMothers Day. Free for a short message with a Mothers Day’ card.",
        pricingText: 109,
        quantity: 1,
        category: "holidays",
        numReviews: 0,
        comments: [],
        brand: "",
        published: true,
        countInStock: true,
        stores: ["home", "holidays", "deals"],
      },
      {
        imageUrl:
          "https://res.cloudinary.com/dgdnpkfun/image/upload/v1656003850/arrangements/cosmoplolitan-design-alt_pmwds2.png",
        id: 19,
        favorite: "add",
        delete: "delete",
        name: "Chic Centerpiece",
        emoji: "💅",
        description:
          "For graduations, bridesmaids or birthday girls. Called chic for its petite shape. This bouquet also can be placed in the vase after the event  is done and turn into a home decor or even as a centerpiece. Mixed spring flowers and use mostly bright and happy colors. So comfortable to hold in your hand, modern and classy.",
        pricingText: 42,
        quantity: 1,
        category: "holidays",
        numReviews: 0,
        comments: [],
        brand: "",
        published: true,
        countInStock: true,
        stores: ["home", "all-occasions", "holidays"],
      },
      {
        imageUrl:
          "https://res.cloudinary.com/dgdnpkfun/image/upload/v1656003850/arrangements/citys-tulips-design_nqwe7c.png",
        id: 20,
        favorite: "add",
        delete: "delete",
        name: "City's Tulips",
        emoji: "🌷",
        description:
          "A gorgeous tulip bouquet with chrysanthemum and a variety of mums and foliages. Accesorized with curly willows to make this bouquet stunning. Available in one or two colors of your choice and in bunches of 18, 24 or 36 tulips.",
        pricingText: 89,
        quantity: 1,
        category: "holidays",
        numReviews: 0,
        comments: [],
        brand: "",
        published: true,
        countInStock: true,
        stores: ["home", "all-occasions", "holidays"],
      },
    ],
  },
  {
    id: 2,
    routeName: "shop/bridal",
    title: "Bridal",
    items: [
      {
        imageUrl:
          "https://res.cloudinary.com/dgdnpkfun/image/upload/w_500,h_550/v1656003850/arrangements/metropolitan-design_fashox.png",
        id: 7,
        favorite: "add",
        delete: "delete",
        name: "Metropolitan",
        emoji: "🌸",
        description:
          "A perfect bouquet to gift for any occasion. The bouquet made as one side view and a bit in long stems they are mixed spring flowers variety of mum, chrysanthemums, roses, lisianthus, tulips, spray roses and some greenish with a variety of foliages to make it so elegant in your hand or when it’s placed in a ceramic water vase (included) on table as a home decor. ",
        pricingText: 58,
        quantity: 1,
        category: "bridal",
        numReviews: 0,
        comments: [],
        brand: "",
        published: true,
        countInStock: true,
        stores: ["home", "all-occasions", "bridal"],
      },
    ],
  },
  {
    id: 3,
    routeName: "shop/well-wishes",
    title: "Well Wishes",
    items: [
      {
        imageUrl:
          "https://res.cloudinary.com/dgdnpkfun/image/upload/v1656003846/arrangements/asymmetric-centerpiece-design_anphoq.png",
        id: 21,
        favorite: "add",
        delete: "delete",
        name: "Asymmetric Centerpiece",
        emoji: "👑",
        pricingText: 60,
        description:
          "The dramatic curve of this asymmetrical arrangement makes for an excellent centerpiece. Its unusual, mystifying shape give an elegant look to your dining table. Predominantly made of roses, along with carnations, hypericum, delphinium, eucalyptus, evangarium, curly willows and foliage.",
        quantity: 1,
        category: "well-wishes",
        numReviews: 0,
        comments: [],
        brand: "",
        published: true,
        countInStock: true,
        stores: ["home", "all-occasions", "well-wishes"],
      },
      {
        imageUrl:
          "https://res.cloudinary.com/dgdnpkfun/image/upload/v1656003848/arrangements/citys-rose-design_dqwdgr.png",
        id: 22,
        favorite: "add",
        delete: "delete",
        name: "City's Rose",
        emoji: "🌹",
        description:
          "A gorgeous roses  bouquet with huckleberry, alstroemeria and foliage accessories with curly willows to make this roses arrangement stunning. Available in one or two colors and in bunches of 18, 24, or 36 roses.",
        pricingText: 25,
        quantity: 1,
        category: "well-wishes",
        numReviews: 0,
        comments: [],
        brand: "",
        published: true,
        countInStock: true,
        stores: ["home", "all-occasions", "well-wishes"],
      },
    ],
  },
  {
    id: 4,
    routeName: "shop/deals",
    title: "Deals",
    items: [
      {
        imageUrl:
          "https://res.cloudinary.com/dgdnpkfun/image/upload/v1657057740/arrangements/city-combo-three-in-one_no0ozp.png",
        id: 24,
        favorite: "add",
        delete: "delete",
        name: "City's Three-In-One Combo",
        emoji: "🎨",
        description: "No Description Available",
        pricingText: 69,
        quantity: 1,
        category: "deals",
        numReviews: 0,
        comments: [],
        brand: "",
        published: true,
        countInStock: true,
        stores: ["home", "all-occasions", "deals"],
      },
      {
        imageUrl:
          "https://res.cloudinary.com/dgdnpkfun/image/upload/v1657057741/arrangements/small-dried-flowers_qvfepx.png",
        id: 25,
        favorite: "add",
        delete: "delete",
        name: "Small Dried Flowers",
        emoji: "💒",
        description: "No Description Available",
        pricingText: 120,
        quantity: 1,
        category: "deals",
        numReviews: 0,
        comments: [],
        brand: "",
        published: true,
        countInStock: true,
        stores: ["home", "all-occasions", "deals"],
      },
      {
        imageUrl:
          "https://res.cloudinary.com/dgdnpkfun/image/upload/v1657057742/arrangements/metropolitan-tropical-2_cgv8p6.png",
        id: 26,
        favorite: "add",
        delete: "delete",
        name: "Metropolitan Tropical Design",
        emoji: "🪐",
        description: "No Description Available",
        pricingText: 35,
        quantity: 1,
        category: "deals",
        numReviews: 0,
        comments: [],
        brand: "",
        published: true,
        countInStock: true,
        stores: ["home", "all-occasions", "deals"],
      },
      {
        imageUrl:
          "https://res.cloudinary.com/dgdnpkfun/image/upload/v1657057743/arrangements/medium-dried-flowers_qifekx.png",
        id: 27,
        favorite: "add",
        delete: "delete",
        name: "Medium Dried Flowers",
        emoji: "❗",
        description: "No Description Availeble",
        pricingText: 60,
        quantity: 1,
        category: "deals",
        numReviews: 0,
        comments: [],
        brand: "",
        published: true,
        countInStock: true,
        stores: ["home", "all-occasions", "deals"],
      },
      {
        imageUrl:
          "https://res.cloudinary.com/dgdnpkfun/image/upload/v1657057747/arrangements/massive-metropolitan_jyj0ht.png",
        id: 28,
        favorite: "add",
        delete: "delete",
        name: "Massive Metropolitan",
        emoji: "❗",
        description: "No Description Available",
        pricingText: 60,
        quantity: 1,
        category: "deals",
        numReviews: 0,
        comments: [],
        brand: "",
        published: true,
        countInStock: true,
        stores: ["home", "all-occasions", "deals"],
      },
      {
        imageUrl:
          "https://res.cloudinary.com/dgdnpkfun/image/upload/v1657057753/arrangements/metropolitan-in-house_vcmktt.png",
        id: 29,
        favorite: "add",
        delete: "delete",
        name: "Metropolitan In-House",
        emoji: "❗",
        description: "No Description Available",
        pricingText: 60,
        quantity: 1,
        category: "deals",
        numReviews: 0,
        comments: [],
        brand: "",
        published: true,
        countInStock: true,
        stores: ["home", "all-occasions", "deals"],
      },
      {
        imageUrl:
          "https://res.cloudinary.com/dgdnpkfun/image/upload/v1657057756/arrangements/metropolitan-bouquet_g9i0pm.png",
        id: 30,
        favorite: "add",
        delete: "delete",
        name: "Metropolitan Bouquet",
        emoji: "❗",
        description: "No Description Available",
        pricingText: 60,
        quantity: 1,
        category: "deals",
        numReviews: 0,
        comments: [],
        brand: "",
        published: true,
        countInStock: true,
        stores: ["home", "all-occasions", "deals"],
      },
      {
        imageUrl:
          "https://res.cloudinary.com/dgdnpkfun/image/upload/v1657057757/arrangements/metropolitan-wedding-package_em4kvs.png",
        id: 31,
        favorite: "add",
        delete: "delete",
        name: "Metropolitan Wedding Combo",
        emoji: "❗",
        description: "No Description Available",
        pricingText: 60,
        quantity: 1,
        category: "deals",
        numReviews: 0,
        comments: [],
        brand: "",
        published: true,
        countInStock: true,
        stores: ["home", "all-occasions", "deals"],
      },
    ],
  },
];

export default SHOP_DATA;
